name: voila-gpx
channels:
  - conda-forge
dependencies:
  - ipyleaflet
  - jupyterlab=0.35
  - ipywidgets=7.4
  - gpxpy
  - pip:
    - ipyupload
    - srtm.py
    - "git+https://github.com/jtpio/voila@data-base-url"

