name: voila-gpx-viewer
channels:
  - conda-forge
dependencies:
  - bqplot=0.11.5
  - ipyleaflet=0.11.0
  - ipywidgets=7.5.0
  - jupyterlab=1
  - gpxpy=1.3.5
  - pandas=0.24
  - pip
  - nodejs
  - pip:
    - srtm.py==0.3.4
    - "git+https://github.com/jtpio/voila.git@5830a748f17fbb50bd7895d9f5c7678e4bbbd366"

