name: voila-gpx-viewer
channels:
  - conda-forge
dependencies:
  - bqplot=0.12
  - ipyleaflet=0.11
  - ipywidgets=7.5
  - jupyterlab=1.2
  - gpxpy=1.3.5
  - pip
  - voila=0.1.20
  - pip:
    - srtm.py==0.3.4

