name: voila-gpx-viewer
channels:
  - conda-forge
dependencies:
  - bqplot=0.11.5
  - ipyleaflet=0.10.8
  - jupyterlab=0.35
  - ipywidgets=7.4
  - gpxpy=1.3.5
  - pandas=0.24
  - pip
  - nodejs
  - voila=0.0.13
  - pip:
    - srtm.py==0.3.4
