name: voila-gpx
channels:
  - conda-forge
dependencies:
  - ipyleaflet=0.10.1
  - jupyterlab=0.35.4
  - ipywidgets=7.4.2
  - gpxpy=1.3.5
  - pandas=0.23.4
  - pip:
    - ipyupload==0.1.3
    - srtm.py==0.3.4
    - "git+https://github.com/jtpio/voila@data-base-url"

