name: voila-gpx
channels:
  - conda-forge
dependencies:
  - ipyleaflet=0.10.1
  - jupyterlab=0.35.4
  - ipywidgets=7.4.2
  - gpxpy=1.3.5
  - pandas=0.23.4
  - pip
  - nodejs  # to build voila from source
  - pip:
    - ipyupload==0.1.3
    - srtm.py==0.3.4
    - "git+https://github.com/QuantStack/voila.git@d33c5f5a04a0fb1769917667fc79ac7d3712af40"
